# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types:
          - svg
      - id: check-yaml
        args:
          - "--unsafe" # Allow tags
      - id: check-added-large-files
  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.11.2
    hooks:
      - id: typos
