cache = true
max_cache_age = "2d"

exclude = [
  '^https://[^.]+\.bit\.edu\.cn',
  '^https://www\.jstor\.org',
  '^http://opinion\.people\.com\.cn',
  ".*'feed_rss_(updated|created).xml'.*",
  # {{ base_url }}
  'file:///.*(%7B){2}(%20)*base_url(%20)*(%7D){2}',
  # {{ … | url }}
  # Remap with name capturing is implemented but not released yet.
  # https://github.com/lycheeverse/lychee/pull/1133
  '''file:///.*(%7B){2}(%20)*'(?P<url>.+)'(%20)*\|(%20)*url(%20)*(%7D){2}''',
]
