cache = true
max_cache_age = "2d"

exclude = [
  # Domain
  '^https://www\.jstor\.org', # 403 Forbidden
  '^https://(www|zhuanlan)\.zhihu\.com', # 403 Forbidden
  '^https://[^.]+\.bit\.edu\.cn', # Too far
  '^http://opinion\.people\.com\.cn', # Too far

  # URL
  # 401 Unauthorized from time to time
  '^https://ai-master\.gitbooks\.io/svm/content/lagrange-multiplier-and-dual-formulation\.html$',

  # MkDocs, etc.
  "'feed_rss_(updated|created).xml'", # To be generated

  # Broken
  # Search engines may still have their indices, however.
  # The links are annotated “(broken 💔)” in `*.md`.

  # 404 Not Found
  # The domain now redirects to https://www.eecs.utk.edu.
  '^https://web\.eecs\.utk\.edu/~azeumaul/',
  # Timeout
  # At first https://www.cs.uic.edu redirects to https://cs.uic.edu, but https://www3.cs.uic.edu is still up.
  # Now they are all down.
  '^https://www3\.cs\.uic\.edu/',
]

remap = [
  # MkDocs, etc.
  # {{ base_url }}
  '^file:///(?P<root>.*)/overrides/(%7B){2}(%20)*base_url(%20)*(%7D){2} file:///$root/docs/',
  # {{ … | url }}
  '''^file:///(?P<root>.*)/overrides/(%7B){2}(%20)*'(?P<url>.+)'(%20)*\|(%20)*url(%20)*(%7D){2}$ file:///$root/docs/$url''',
]

# Otherwise, mathworks.com and other websites might response 403 Forbidden.
user_agent = "curl/8.9.1"
