cache = true
max_cache_age = "2d"

exclude = [
  # Domain
  '^https://www\.jstor\.org', # 403 Forbidden
  '^https://[^.]+\.bit\.edu\.cn', # Too far
  '^http://opinion\.people\.com\.cn', # Too far

  # URL
  # Expired certificate
  '^https://www3\.cs\.uic\.edu/pub/ECE534/WebHome/ch2\.pdf$',
  '^https://eeweb\.engineering\.nyu\.edu/iselesni/EL713/zoom/linphase\.pdf$',
  '^https://www2\.stat\.duke\.edu/',
  # 401 Unauthorized from time to time
  '^https://ai-master\.gitbooks\.io/svm/content/lagrange-multiplier-and-dual-formulation\.html$',

  # MkDocs, etc.
  "'feed_rss_(updated|created).xml'", # To be generated
]

remap = [
  # MkDocs, etc.
  # {{ base_url }}
  '^file:///(?P<root>.*)/overrides/(%7B){2}(%20)*base_url(%20)*(%7D){2} file:///$root/docs/',
  # {{ … | url }}
  '''^file:///(?P<root>.*)/overrides/(%7B){2}(%20)*'(?P<url>.+)'(%20)*\|(%20)*url(%20)*(%7D){2}$ file:///$root/docs/$url''',
]
