name: check
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          args: >-
            --verbose
            --no-progress
            --config .github/config/lychee.toml
            .
