name: check
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/mlc_config.json"
